name: gate-api
services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_cerberus}"
    image: localstack/localstack-pro 
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - LOCALSTACK_AUTH_TOKEN="ls-RiFIdoqO-PUpu-FOTO-NaXi-4708XuPA470c"
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=lambda,sns,sqs,s3,cloudformation,cloudwatch,sts,ssm,iam,apigateway,secretsmanager,logs,events,cognito-idp # Para obter lista completa => http GET http://127.0.0.1:4566/_localstack/health
      - EXTRA_CORS_ALLOWED_ORIGINS=https://app.localstack.cloud. # Enable access from the dashboard
    volumes:
      - "./localstack-volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  gate.api:
    image: ${DOCKER_REGISTRY-}gateapi
    ports:
     - "8080:8080"
    build:
      context: src
      dockerfile: Gate.Api/Dockerfile
    environment:
      LocalStack__Config__LocalStackHost: 'localstack'
    depends_on:
      - localstack