name: cerberus-api
services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_orbia_accept_package}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-:1} # 1 para ativar
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=${PERSISTENCE-}
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=lambda,sns,sqs,s3,cloudformation,cloudwatch,sts,ssm,iam,apigateway,secretsmanager,logs,events,stepfunctions # Para obter lista completa => http GET http://127.0.0.1:4566/_localstack/health
      - EXTRA_CORS_ALLOWED_ORIGINS=https://app.localstack.cloud. # Enable access from the dashboard
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-init:/etc/localstack/init/ready.d"

  cerberus-api:
    container_name: cerberus-api
    image: lkhouri/cerberus-api:latest
    ports:
     - "5000:80"
    build:
      context: .
      dockerfile: Api\Dockerfile
    environment:
      LocalStack__Config__LocalStackHost: 'localstack'
    depends_on:
      - localstack
    volumes:
     - ./Api/Cerberus.Api:/appsettings.json
